/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://cyvig7wazzci5a5q7h72psqvzq.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-glzx63t4jzg35cbv44nbafrlfy",
    "aws_cognito_identity_pool_id": "ap-south-1:f9ff6f66-824f-4a6b-92ae-d6fca1f1ce65",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_wWqLXxaa4",
    "aws_user_pools_web_client_id": "71gt6gk9jjil71rjvseimb6hr2",
    "oauth": {}
};


export default awsmobile;
